Revert "techpack: audio: tfa98xx: Fix VLA violation ../techpack/audio/asoc/codecs/tfa98xx-v6/tfa98xx_v6.c:482:14: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension] char buffer[size]; ^~~~wq"
This reverts commit 464c7b57d73904ca728cf8bc3d5b39100500c481.